app = "{{todo}}"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
dockerfile = "Dockerfile"

[env]
DATABASE_URL = "file:/data/{{todo}}.db"
LOFI_DB_FILE = "/data/{{todo}}-lofi.db"
HOST = "https://{{todo}}.todo"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
internal_port = 3001
protocol = "tcp"
[services.concurrency]
type = "connections"
# don't limit websocket connections
hard_limit = 10000
soft_limit = 10000

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.http_checks]]
interval = 10000
grace_period = "5s"
method = "get"
path = "/"
protocol = "http"
restart_limit = 0
timeout = 2000
tls_skip_verify = false

[mounts]
source = "{{todo}}_data"
destination = "/data"
